# Generated by Django 5.0.6 on 2025-12-10 06:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancechange_attendancereport_classschedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='late_entry_time',
            field=models.DateTimeField(blank=True, help_text='Exact time student was detected if marked as late', null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='semester_old',
            field=models.CharField(blank=True, default='Spring 2024', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='grace_period_minutes',
            field=models.IntegerField(default=10, help_text='Grace period in minutes before marking late (default: 10 minutes)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='semester_old',
            field=models.CharField(blank=True, default='Spring 2024', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='teaching_department',
            field=models.ForeignKey(blank=True, help_text="Department where this subject is taught (may differ from teacher's home department)", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='attendance.department'),
        ),
        migrations.AlterField(
            model_name='teacherassignment',
            name='cross_department',
            field=models.BooleanField(default=False, help_text='True if teacher is teaching outside their home department'),
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6'), (7, 'Semester 7'), (8, 'Semester 8')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('academic_year', models.CharField(default='2024-2025', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('upcoming', 'Upcoming')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='attendance.department')),
            ],
            options={
                'ordering': ['department', 'number'],
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='attendance.semester'),
        ),
        migrations.AlterField(
            model_name='class',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='attendance.semester'),
        ),
        migrations.AlterField(
            model_name='teacherassignment',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='attendance.semester'),
        ),
        migrations.AddIndex(
            model_name='semester',
            index=models.Index(fields=['department', 'number'], name='attendance__departm_e6d798_idx'),
        ),
        migrations.AddIndex(
            model_name='semester',
            index=models.Index(fields=['academic_year'], name='attendance__academi_818460_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('number', 'department', 'academic_year')},
        ),
    ]
