# Generated by Django 5.0.6 on 2025-12-10 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendance_late_entry_time_class_semester_old_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='semester_old',
        ),
        migrations.RemoveField(
            model_name='teacherassignment',
            name='semester_old',
        ),
    ]
