# Generated by Django 5.0.6 on 2025-12-16 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_enforce_hod_required'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['code']},
        ),
    ]
