# Generated by Django 5.0.6 on 2025-12-16 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_alter_department_options'),
        ('users', '0003_customuser_department_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='semester',
            field=models.ForeignKey(blank=True, help_text='Current semester for students', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='attendance.semester'),
        ),
    ]
